# Generated by Django 5.2.4 on 2025-09-12 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_syllabus_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='helpful_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='unhelpful_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='users_voted',
            field=models.ManyToManyField(blank=True, related_name='voted_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
